version: '3.4'

#SERVICES
services:
  #Frontend
  reactjs:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules


